//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanlyEntities : DbContext
    {
        public QuanlyEntities()
            : base("name=QuanlyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DanhMucLoi> tbl_DanhMucLoi { get; set; }
        public virtual DbSet<tbl_GiaoVien> tbl_GiaoVien { get; set; }
        public virtual DbSet<tbl_GiaoVien_Lop> tbl_GiaoVien_Lop { get; set; }
        public virtual DbSet<tbl_HocKy> tbl_HocKy { get; set; }
        public virtual DbSet<tbl_HocSinh> tbl_HocSinh { get; set; }
        public virtual DbSet<tbl_KetQua> tbl_KetQua { get; set; }
        public virtual DbSet<tbl_Lop> tbl_Lop { get; set; }
        public virtual DbSet<tbl_MonHoc> tbl_MonHoc { get; set; }
        public virtual DbSet<tbl_NamHoc> tbl_NamHoc { get; set; }
        public virtual DbSet<tbl_Truong> tbl_Truong { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_ViPham> tbl_ViPham { get; set; }
        public virtual DbSet<tbl_ViPham_CT> tbl_ViPham_CT { get; set; }
    }
}
