//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lop
    {
        public int MaLop { get; set; }
        public string TenLop { get; set; }
        public string GhiChu { get; set; }
        public string SapXep { get; set; }
        public string MaTruong { get; set; }
    }
}
