//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KetQua
    {
        public int MaKQ { get; set; }
        public Nullable<int> MaMH { get; set; }
        public Nullable<int> MaHS { get; set; }
        public Nullable<double> DiemTK { get; set; }
        public Nullable<double> DiemThiLan1 { get; set; }
        public Nullable<double> DiemThiLan2 { get; set; }
        public Nullable<double> DiemTB { get; set; }
        public string XepLoai { get; set; }
        public Nullable<int> MaNamHoc { get; set; }
        public Nullable<int> MaHocKy { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> CrearedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
